### ISSUE TITLE
Suggestion compatibility 1.7.10

### ISSUE THREAD

**Issue by llaya** [kreezxil/BadWitherNoCookie#2]
Is there any chance you could make a version that is compatible with 1.7.10.

**Comment by kreezxil** [comment]
There's a slim chance. I've tried and the system is drastically different
below the lowest version of forge I have this for. Which modpack will it
being going into and how many downloads per month is that pack getting?

**Comment by llaya** [comment]
I was kinda hoping to use it with SkyFactory2.5. Either-preinstalled from the server out, or client side.
Especially on servers the dragondeathsound can be pretty earblasting and if 1 dweep has a farm, the rest of the players go deaf. We have a pretty steady and large playercount on a daily basis, and apart from sky factory 2.5 that is just such a popular modpack, there's still other modpacks being created on 1.7.10.

If you don't have time to make it backwards compatible i would definately understand tho :)

**Comment by kreezxil** [comment]
I'll see what I can do. Can you please link me your pack. thanks.

**Comment by llaya** [comment]
Will this do?
https://www.feed-the-beast.com/projects/ftb-presents-skyfactory-2-5

**Comment by kreezxil** [comment]
As I suspect, not your pack, a pack that you are using yes, but not your
creation. Nothing new has been done for that pack since Nov 2, 2016.
Contrary to what you think not many people are downloading and playing it
either. Just because it has it's own tab on Twitch Launcher doesn't mean
much, click "Browse all Packs" are better overview of what's really
happening in the modpack community.

So to get me to code for 1.7.10 which is hard as heck compared to 1.12.2,
and keep in mind here what we are wanting to is backport all the
Functionality of this mod to that level ... is going to take a lot of work
and effort.

I have a lot of current projects on CurseForge already as seen at
http://minecraft.curseforge.com/members/kreezxil/projects and maintain half
of them on a regular basis. **World of Dragons** Mod Pack which is mine is
maintained/updated at least twice a week and has included public servers.

The point here is that for you to get me to recode the mod to work in
1.7.10 for a pack that is not updated nor downloaded very much is gonna
cost at least $50. That's what I make monthly from my efforts on CurseForge
which would stop if I have to dissect my mod and learn why it doesn't
easily work on 1.7.10 and then rebuild it from scratch so that it will work
on 1.7.10. I'll lose a month coding this.

Conversely, you can find a 1.7.10 coder and ask them to fork my project and
build a 1.7.10 version of it and submit it back to me as a pr for the new
branch, I'll see that, merge the branch, compile a 1.7.10 version and then
you'll have it. The steps in this paragraph won't require money from me,
but that coder might want money, 1.7.10 is sooo old now.

**Comment by kreezxil** [comment]
Insanity.
